-- rss.xml — RSS 2.0 feed for blog articles
-- Copyright 2026 Vivian Voss. All rights reserved.

local SITE = "https://vivianvoss.net"

local articles = {
    { date = "Wed, 29 Apr 2026 00:00:00 GMT", title = "A Small Adventure Between Two Prices", loc = "/blog/publisher-shop-launch", desc = "Amazon since World Book Day, the publisher's direct shop six days later. The gap was not laziness: Amazon arithmetic (60% above threshold, 40-50% net), the German Buchpreisbindungsgesetz (one fixed price for everyone, the publisher included), the One-Stop-Shop quarterly tax window (filed April, effective 1 July), and Stripe's merchant geography. Hardcover 90 EUR, paperback 80 EUR, hand-signed direct. PDF and ePub 40 EUR each, direct-only." },
    { date = "Tue, 28 Apr 2026 00:00:00 GMT", title = "pf", loc = "/blog/pf", desc = "In May 2001 OpenBSD pulled IPFilter out of the source tree over a licence dispute. Daniel Hartmeier, who had never written kernel code, replaced it in twenty-five days. By 1 December 2001 it shipped in OpenBSD 3.0. Twenty-five years on, pf is the firewall in OpenBSD, FreeBSD, NetBSD, DragonFly and macOS, runs on roughly a billion Apple devices, and Linux's nftables (2014) is rather quietly an admission that pf had the right shape." },
    { date = "Mon, 27 Apr 2026 00:00:00 GMT", title = "What the Bootloader Knows", loc = "/blog/what-the-bootloader-knows", desc = "Between firmware that knows almost nothing and a kernel that must know everything sits a small program with a strange job. FreeBSD loader: ~600 KB Forth, ZFS-aware Boot Environment menu. LILO (1992-2015): block lists. GRUB 2: an operating system before the operating system. Three theories of the OS." },
    { date = "Sun, 26 Apr 2026 00:00:00 GMT", title = "Why We Measure Tickets, Not Problems Prevented", loc = "/blog/why-we-measure-tickets", desc = "The dashboard is green. Production has been quietly fragile for eleven weeks. Taylor 1911, Goodhart 1975, Strathern 1997, Jeffries 2019: we were warned by name. The engineer who prevents three outages closes zero tickets and is invisible. The one who closes forty-seven is promoted. The chair, somewhere, is not being built." },
    { date = "Sat, 25 Apr 2026 00:00:00 GMT", title = "The Dependency Avalanche", loc = "/blog/dependency-avalanche", desc = "Express resolves 65 packages, 3.6 MB. Next.js (create-next-app defaults) resolves 644 packages, 463 MB, to render eighteen characters of text. XZ CVE-2024-3094: 2.5 years of patient social engineering against an unpaid maintainer, caught by Andres Freund noticing 500 ms of SSH latency. Next time it might be 50." },
    { date = "Fri, 24 Apr 2026 00:00:00 GMT", title = "Service Mesh: The Sidecar Tax", loc = "/blog/service-mesh-sidecar-tax", desc = "mTLS, observability, zero-code retries. Splendid. CNCF 2024 Survey: mesh adoption 42%, down from 50%. 2025 peer-reviewed benchmark: Istio sidecar +166% mTLS latency, Linkerd +33%, Istio Ambient +8%. 60 MB RAM per pod, 60 GB across a 1,000-pod cluster before code runs. Ambient is Istio's own admission." },
    { date = "Thu, 23 Apr 2026 00:00:00 GMT", title = "Integrated by Design — Launch Day", loc = "/blog/integrated-by-design-launch", desc = "Launch day for Integrated by Design, 371 pages on FreeBSD, on UNESCO World Book Day. Five months of writing, three weeks of final proofs, then 72 hours of the problems one does not anticipate: one unclosed counter on the number 8, invisible adjustment layers in a cover PDF, a KDP form that says list price and means net, a Kindle in Amazon's review queue." },
    { date = "Wed, 22 Apr 2026 00:00:00 GMT", title = "The CSS Scope You Never Had to Compile", loc = "/blog/css-scope", desc = "Every web developer has fought this fight: .card h3 colliding with a third-party widget. BEM, CSS Modules, 80 KB of styled-components. @scope is the native answer: zero specificity, a new cascade tier called scoping proximity, cross-browser stable since December 2025. The cascade, after twenty-five years, is finally finished." },
    { date = "Tue, 21 Apr 2026 00:00:00 GMT", title = "Markdown", loc = "/blog/markdown", desc = "On 15 March 2004, John Gruber posted a blog entry and a 1,400-line Perl script. Aaron Swartz was the sole beta-tester. No lexer, no parser, no AST. Twenty-one years later, GitHub, Reddit, Notion, and every major LLM speak Markdown. Third year running as the most admired documentation format. Plain text won." },
    { date = "Mon, 20 Apr 2026 00:00:00 GMT", title = "The Snapshot That Travels", loc = "/blog/the-snapshot-that-travels", desc = "At 3 AM on a production cluster measured in terabytes, the question is whether any of your backup tools will finish before breakfast. ZFS snapshot, send, clone: atomic in milliseconds, 40 TB delta in seconds, copy-on-write branches at zero cost. Backup, replication, and branching are three uses of the same primitive." },
    { date = "Sun, 19 Apr 2026 00:00:00 GMT", title = "Why We Accepted Surveillance as Default", loc = "/blog/why-we-accepted-surveillance", desc = "In January 1996, two men in New York founded DoubleClick. Nobody voted on this. 7 trackers per page, 600 billion bid requests per day, 90% accept when Reject all is hidden. Apple ATT 2021: one OS prompt, -$10B Meta revenue. The technology was always there." },
    { date = "Sat, 18 Apr 2026 00:00:00 GMT", title = "The Compute-Is-Cheap Decade", loc = "/blog/compute-is-cheap-decade", desc = "Knuth's quote was 97%/3%. Only the 97% survived. Discord rewrote Go in Rust: memory down 40%, latency 160x. Twitter decommissioned 148,000 servers and continued to function. WhatsApp 2015: fifty engineers for 900 million users. Data centres: 415 TWh in 2024, 945 TWh projected by 2030." },
    { date = "Fri, 17 Apr 2026 00:00:00 GMT", title = "Auth0: The Identity Tax", loc = "/blog/auth0-identity-tax", desc = "Okta paid $6.5B for a company doing $200M in revenue. The arithmetic suggests the customer pays the difference. 300% per-MAU hike in one announcement. Two breaches, every customer's name and email exfiltrated. The password hash was always there." },
    { date = "Thu, 16 Apr 2026 00:00:00 GMT", title = "Redis: The One-Thread Design", loc = "/blog/redis-single-thread", desc = "In 2009, Salvatore Sanfilippo made Redis single-threaded. A contested mutex costs 10,000 CPU cycles. Redis makes contention structurally impossible. 1.5 million operations per second, one core, commodity hardware. The limitation is the architecture. The architecture is the feature." },
    { date = "Wed, 15 Apr 2026 00:00:00 GMT", title = "The Deep Clone You Never Had to Install", loc = "/blog/structured-clone", desc = "JSON.parse(JSON.stringify()) destroys Date, Map, Set, RegExp, and throws on circular references. structuredClone handles all of them. Zero KB. Built in since 2022. Lodash cloneDeep: 17 KB, unchanged for a decade." },
    { date = "Tue, 14 Apr 2026 00:00:00 GMT", title = "ssh-agent", loc = "/blog/ssh-agent", desc = "2,624 lines of C. One file. One socket. No config. The private key never leaves the process. Born from impatience in 1995, designed with discipline, still the authentication backbone of every CI/CD system on earth." },
    { date = "Mon, 13 Apr 2026 00:00:00 GMT", title = "periodic", loc = "/blog/periodic", desc = "cron tells you when. periodic tells you what happened. FreeBSD: one config file, severity-coded output, daily email. OpenBSD: pledge/unveil violation reports. Linux: twenty files for ten tasks. The problem was never scheduling. It was accountability." },
    { date = "Sun, 12 Apr 2026 00:00:00 GMT", title = "Why the Cloud Is the Default", loc = "/blog/why-the-cloud-is-the-default", desc = "27% of cloud spend wasted ($182B/year). 37signals saved $10M+ leaving AWS. Ahrefs: 11.3x cheaper on-prem. 86% of CIOs plan repatriation. The cloud was the only answer nobody got fired for choosing." },
    { date = "Sat, 11 Apr 2026 00:00:00 GMT", title = "The Feature Creep", loc = "/blog/the-feature-creep", desc = "Notion: notes to email client. Jira: bug tracker to 3,000 plugins. Google: 299 products killed. Sonos: CEO resigned. Skype: 405M to shutdown. VLC: media player since 2001. The best software never added the wrong features." },
    { date = "Fri, 10 Apr 2026 00:00:00 GMT", title = "The Certification Industrial Complex", loc = "/blog/certification-industrial-complex", desc = "$700 exam. Expires in 3 years. Repeat. Non-certified skills earn 2% more since 2007. CompTIA: $168M/year, now PE-owned. Kent Beck called it a pyramid scheme. When private equity acquires the exam, the product is you." },
    { date = "Thu, 09 Apr 2026 00:00:00 GMT", title = "Rust Says No", loc = "/blog/rust-says-no", desc = "No null. No exceptions. No garbage collector. No inheritance. In 2006, Graydon Hoare walked up 21 floors because his elevator crashed. Memory bug. C code. He started writing Rust. Every no eliminates a category of bugs. The elevator stops crashing." },
    { date = "Wed, 08 Apr 2026 00:00:00 GMT", title = "The Page Transition You Never Had to Build", loc = "/blog/view-transitions", desc = "We shipped 400KB of JavaScript so a heading could fade. The browser does it now. Three lines of CSS. Zero JavaScript. View Transition API: 0KB. 87.82% global coverage. Progressive enhancement, done properly." },
    { date = "Tue, 07 Apr 2026 00:00:00 GMT", title = "DTrace", loc = "/blog/dtrace", desc = "Zero overhead when probes are disabled. Safe by construction. Concise answers to arbitrary questions. DTrace solved production observability in 2003. FreeBSD ships it in base. Logging records what you predicted. DTrace answers what you never thought to ask." },
    { date = "Mon, 06 Apr 2026 00:00:00 GMT", title = "The Philosophy", loc = "/blog/the-unix-philosophy", desc = "In 1978, Doug McIlroy wrote four sentences. They have outlasted every framework since. Do one thing well. Text as universal interface. Silence is golden. FreeBSD, macOS, OpenBSD: the systems that follow the philosophy outlast the systems that ignore it." },
    { date = "Sun, 05 Apr 2026 00:00:00 GMT", title = "Why We Teach Tools Instead of Foundations", loc = "/blog/why-we-teach-tools", desc = "In the 1990s, CS taught foundations. In 2026, it teaches React. Alan Kay warned us in 2004. MIT proved him right in 2020. 250,000 Kubernetes certifications. One does wonder how many could explain what a process is." },
    { date = "Sun, 05 Apr 2026 00:00:00 GMT", title = "AI Code Generation: The Hallucination Tax", loc = "/blog/ai-code-generation", desc = "METR: developers 19% slower with AI (believed 20% faster). 19.6% of recommended packages do not exist. 40% of Copilot output contains vulnerabilities. Refactoring collapsed from 25% to under 10%. Write lean. The AI will follow." },
    { date = "Sat, 04 Apr 2026 00:00:00 GMT", title = "The Update Treadmill", loc = "/blog/the-update-treadmill", desc = "Your software worked on Friday. npm update broke it on Monday. Angular: 18 major versions in 10 years. 75% of dev time on maintenance. SQLite: backwards-compatible since 2004. The treadmill is not inevitable. It is profitable." },
    { date = "Fri, 03 Apr 2026 00:00:00 GMT", title = "JavaScript Backend: The Full-Stack Tax", loc = "/blog/javascript-backend", desc = "Built in ten days for form validation. Express: 20K RPS. Rust: 60K. Idle memory: 30-50 MB vs 1-2 MB. One thread. 500K malicious npm packages. The creator called node_modules an irreparable mistake and built Deno." },
    { date = "Thu, 02 Apr 2026 00:00:00 GMT", title = "CSV: The Format Nobody Designed", loc = "/blog/by-design-csv", desc = "In 1972, IBM separated values with commas. No specification. No committee. Thirty-three years later, someone wrote the RFC. 60% of enterprises still use CSV. The format that requires no agreement outlasts the format that requires consensus." },
    { date = "Wed, 01 Apr 2026 00:00:00 GMT", title = "The Native Popover That Positions Itself", loc = "/blog/popover-anchor", desc = "Floating UI: 35KB. Popper.js: 28KB. Tippy.js: 22KB. The native equivalent: zero kilobytes. The Popover API handles visibility, z-index, light dismiss, and keyboard. CSS Anchor Positioning handles placement and viewport flipping." },
    { date = "Tue, 31 Mar 2026 00:00:00 GMT", title = "Let's Encrypt", loc = "/blog/lets-encrypt", desc = "Before 2015, HTTPS was a luxury. A certificate cost $50 and a week of manual process. Then four people decided this was absurd. 700 million websites. 10 million certificates per day. Ten years. Zero pounds." },
    { date = "Mon, 30 Mar 2026 00:00:00 GMT", title = "The .env File Nobody Needs", loc = "/blog/the-env-file", desc = "107 million weekly downloads for dotenv. A package that reads KEY=VALUE pairs from a file. Unix has done this since 1979. GitHub detected 39 million leaked secrets in 2024. Even Node.js shipped --env-file natively." },
    { date = "Sun, 29 Mar 2026 00:00:00 GMT", title = "Google Search: The Time Tax", loc = "/blog/search-quality", desc = "30% of a knowledge worker's day spent searching. Google's trust score dropped from 7.05 to 5.73 in one year. 83% zero-click rate with AI Overviews. The search engine that once finished your sentence now wastes your afternoon." },
    { date = "Sat, 28 Mar 2026 00:00:00 GMT", title = "The Quality Erosion", loc = "/blog/the-quality-erosion", desc = "In 2023, Klarna replaced 700 support agents with AI. Costs down 25%. In 2025, they started rehiring humans. 64% of customers prefer no AI in support. 41% higher code churn. 19% slower with AI tools. The tool is neutral. The incentive is not." },
    { date = "Fri, 27 Mar 2026 00:00:00 GMT", title = "qq", loc = "/blog/bytes-of-art-qq", desc = "64 kilobytes. Three minutes of architectural hallucination by Quite. Corridors fold into corridors. Every frame calculated in real time from a single executable built with Werkkzeug1. First place at DiHALT 2012." },
    { date = "Fri, 27 Mar 2026 00:00:00 GMT", title = "GraphQL: The Query Tax", loc = "/blog/graphql", desc = "In 2012, Facebook had a problem: hundreds of microservices, a mobile News Feed, constrained bandwidth. They built GraphQL. The solution was brilliant. For Facebook. You have 12 REST endpoints and a fetch() call." },
    { date = "Thu, 26 Mar 2026 00:00:00 GMT", title = "The Single Writer", loc = "/blog/by-design-sqlite", desc = "In 2000, D. Richard Hipp built a database for a U.S. Navy destroyer. The existing Informix installation required a DBA. Hipp's solution was not to fix the server. It was to eliminate it entirely. 600 KB. One file. Zero configuration. The most deployed software module in history." },
    { date = "Tue, 25 Mar 2026 00:00:00 GMT", title = "Server-Sent Events", loc = "/blog/sse", desc = "Most real-time features are one-way. The browser solved this in 2015 with one line of JavaScript that nobody teaches. No npm. No reconnect logic. EventSource reconnects automatically. The specification demands it." },
    { date = "Tue, 24 Mar 2026 00:00:00 GMT", title = "vi", loc = "/blog/vi", desc = "2.7 million people have visited Stack Overflow to learn how to exit a text editor. The most feared tool in computing is also the most elegant. A composable grammar born from a 300 baud modem. Fifty years of production." },
    { date = "Mon, 23 Mar 2026 00:00:00 GMT", title = "The Log", loc = "/blog/the-log", desc = "Eric Allman wrote syslog in the 1980s. Forty years of production. Zero licence fees. Log rotation, live monitoring, frequency analysis, and alerting. Four commands. Each composable. Each free." },
    { date = "Sun, 22 Mar 2026 00:00:00 GMT", title = "Why Mathematicians Design Languages", loc = "/blog/why-mathematicians-design-languages", desc = "Every mainstream programming language was designed by a mathematician. Not one linguist in the room. Ninety years later, we are still writing in their notation. One does wonder what might have happened if someone had invited one." },
    { date = "Sun, 22 Mar 2026 00:00:00 GMT", title = "The Observability Tax", loc = "/blog/the-observability-tax", desc = "syslog has existed since 1983. In 2026, a mid-sized company spends $708,000 per year to know whether its servers are running. 97% report cost surprises. The watchtower now costs more than the castle." },
    { date = "Sat, 21 Mar 2026 00:00:00 GMT", title = "The Electron Tax", loc = "/blog/the-electron-tax", desc = "Every Electron app ships its own copy of Chromium. Slack, Discord, Teams, VS Code. Four apps, four browsers, none displaying a web page. The company saves on engineering. The user pays in RAM, battery, and disk space." },
    { date = "Fri, 20 Mar 2026 00:00:00 GMT", title = "Terraform: The Abstraction Layer", loc = "/blog/terraform", desc = "You wanted to provision a server. You got a proprietary language that cannot express a conditional, a state file that stores your secrets in plain text, and a licence that changed overnight. Three invoices for one abstraction." },
    { date = "Thu, 19 Mar 2026 00:00:00 GMT", title = "Hydration", loc = "/blog/hydration", desc = "In 1995, PHP rendered HTML on the server. In 2026, the industry renders HTML on the server, then ships 558 KB of JavaScript to rebuild the same DOM. They call this hydration. Twenty years to return to where PHP started." },
    { date = "Wed, 18 Mar 2026 00:00:00 GMT", title = "The Form the Browser Already Validated", loc = "/blog/form-validation", desc = "The average React project installs a validation library before a single input field exists. The browser has validated forms natively since 2014. Required, email, pattern, minlength. No JavaScript. No bundle size." },
    { date = "Tue, 17 Mar 2026 00:00:00 GMT", title = "The Pipe", loc = "/blog/the-pipe", desc = "In 1964, Douglas McIlroy wrote a memo about coupling programmes like garden hose. Nine years later, Ken Thompson implemented it overnight. One character. The most elegant composition model in computing, fifty-three years unchanged." },
    { date = "Mon, 16 Mar 2026 00:00:00 GMT", title = "The Origin", loc = "/blog/the-unix-origins", desc = "In 1969, Ken Thompson wanted to play Space Travel. The mainframe cost $75 per session. So he found a PDP-7 with 9 KB of memory and built an operating system. Its descendants run most of the world." },
    { date = "Sun, 15 Mar 2026 00:00:00 GMT", title = "The Next.js Tax", loc = "/blog/the-nextjs-tax", desc = "React ships 136 KB to the browser. Next.js promised to fix that. 247 MB of node_modules, 87 KB client runtime, hydration that doubles every render, and vendor lock-in disguised as developer experience." },
    { date = "Sat, 14 Mar 2026 00:00:00 GMT", title = "The Early Access Alibi", loc = "/blog/the-early-access-alibi", desc = "Early access was invented so a solo developer in Stockholm could finish a game about mining blocks. Then publishers noticed. They copied the label. Not the honesty. 25,000 jobs lost at record revenue." },
    { date = "Fri, 13 Mar 2026 00:00:00 GMT", title = "Jira: The Workflow Tax", loc = "/blog/jira", desc = "You wanted to track bugs. You got a bureaucracy engine with custom fields nobody remembers creating and workflows nobody dares to simplify. 68% of new users overwhelmed. 1-4 seconds per issue. 883 sites deleted. The Jira invoice, itemised." },
    { date = "Thu, 12 Mar 2026 00:00:00 GMT", title = "Clean Code: The Prescription That Outlived the Diagnosis", loc = "/blog/clean-code", desc = "Robert C. Martin published Clean Code in 2008 to fix Java enterprise monoliths with no structure. The industry copied the rules and forgot the context. A prescription without a diagnosis." },
    { date = "Wed, 11 Mar 2026 00:00:00 GMT", title = "Bytes of Art: 0mix", loc = "/blog/bytes-of-art-0mix", desc = "64 kilobytes. A seven-minute techno live set with procedural visuals and synthesised audio, running in your browser. Won Best Soundtrack at The Meteoriks 2024 against every production of the year." },
    { date = "Wed, 11 Mar 2026 00:00:00 GMT", title = "Native WebSocket: Server Pushes, Client Listens", loc = "/blog/websocket", desc = "Your frontend needs live data. React taught an entire generation of developers to poll. The browser solved this in 2011 with two lines of JavaScript and zero npm packages." },
    { date = "Mon, 10 Mar 2026 00:00:00 GMT", title = "diff: The Tool That Enabled Collaboration", loc = "/blog/technical-beauty-diff", desc = "In 1974, James Hunt and Douglas McIlroy built diff at Bell Labs. Two files in, one output: what changed. Every code review, every pull request, every version control system since RCS stores history as diffs. 52 years in production. No subscription." },
    { date = "Sun, 09 Mar 2026 00:00:00 GMT", title = "SSH Config: The File Nobody Reads", loc = "/blog/ssh-config", desc = "You type ssh -i ~/.ssh/prod_key -p 2222 deploy@192.168.50.12 fourteen times a day. There is a plain text file that reduces this to ssh prod. It has existed since 1999. One file. No GUI. No subscription." },
    { date = "Sat, 08 Mar 2026 00:00:00 GMT", title = "The Distributed Tax", loc = "/blog/the-distributed-tax", desc = "A function call costs 0.001 ms. A network call between two microservices costs 1 to 5 ms. That is factor 5,000 before any business logic executes." },
    { date = "Fri, 07 Mar 2026 00:00:00 GMT", title = "The Enshittification Cycle", loc = "/blog/the-enshittification-cycle", desc = "Cory Doctorow named it. You have lived it. Every platform begins by being useful, then monetises its users, then monetises its business customers, then dies." },
    { date = "Thu, 06 Mar 2026 00:00:00 GMT", title = "Rolling Releases: The Perpetual Beta", loc = "/blog/rolling-releases", desc = "Software used to ship when it was ready. Now it ships when the sprint ends. Chrome halved its release cycle twice. CrowdStrike pushed one update and crashed 8.5 million machines." },
    { date = "Wed, 05 Mar 2026 00:00:00 GMT", title = "BEM: The Naming Convention That Named Itself Indispensable", loc = "/blog/bem", desc = "BEM was invented at Yandex to stop CSS from breaking across 100 services. The industry adopted it to name twelve classes on a landing page." },
    { date = "Tue, 04 Mar 2026 00:00:00 GMT", title = "The Server Question", loc = "/blog/the-server-question", desc = "72% of the web runs on PHP. Not an accident. But the web has moved: persistent connections, live pushes, minimal memory. Five languages, one task, a 128x difference in memory." },
    { date = "Mon, 03 Mar 2026 00:00:00 GMT", title = "Technical Beauty: jq", loc = "/blog/technical-beauty-jq", desc = "In 2012, JSON was the lingua franca of the web and the Unix toolbox had nothing for it. One PhD student at Cambridge wrote a functional language in 510 KB of C." },
    { date = "Sun, 02 Mar 2026 00:00:00 GMT", title = "Capsicum vs seccomp: Process Sandboxing", loc = "/blog/capsicum-vs-seccomp", desc = "A compromised process inherits the full authority of the user who launched it. Two operating systems fixed this with opposite philosophies." },
    { date = "Sat, 01 Mar 2026 00:00:00 GMT", title = "GraphQL: The Query You Didn't Need", loc = "/blog/the-graphql-tax", desc = "GraphQL was built at Facebook for the News Feed. REST is 50% faster on relational databases. 34x faster with eager loading. The performance tax, itemised." },
    { date = "Sat, 28 Feb 2026 00:00:00 GMT", title = "The Permanent Beta", loc = "/blog/the-permanent-beta", desc = "Software used to come on a disc. A bug on a pressed CD was a recall, not a hotfix. Then the internet removed the disc." },
    { date = "Fri, 27 Feb 2026 00:00:00 GMT", title = "SaaS: The Subscription Tax", loc = "/blog/the-saas-tax", desc = "In 2012, you could buy Adobe Creative Suite for $2,599. You owned it. In 2026, you pay $660 per year and own nothing." },
    { date = "Thu, 26 Feb 2026 00:00:00 GMT", title = "The Kernel Question", loc = "/blog/the-kernel-question", desc = "Europe wants digital sovereignty but builds on a kernel governed by US corporations. 84.3% of Linux commits, $500K board seats." },
    { date = "Thu, 26 Feb 2026 00:00:00 GMT", title = "Containerise Everything", loc = "/blog/containerise-everything", desc = "Docker solved deployment. Then the industry decided it also solved development. On macOS, that means running a Linux VM to execute a process that runs natively." },
    { date = "Wed, 25 Feb 2026 00:00:00 GMT", title = "CSS Learns to Think", loc = "/blog/css-learns-to-think", desc = "For twenty-three years, CSS could only look downward. A parent styled its children. Never the reverse. In 2023, three pseudo-classes changed the direction of the cascade." },
    { date = "Wed, 25 Feb 2026 00:00:00 GMT", title = "Why Every Byte Matters", loc = "/blog/why-every-byte-matters", desc = "The demoscene taught a generation that constraint is not limitation; it is method. Every instruction must justify its presence." },
    { date = "Tue, 24 Feb 2026 00:00:00 GMT", title = "make: Three Concepts, Fifty Years", loc = "/blog/technical-beauty-make", desc = "1976. Stuart Feldman writes make in a weekend. Targets, dependencies, timestamps. Three concepts. Fifty years. Same algorithm." },
    { date = "Mon, 23 Feb 2026 00:00:00 GMT", title = "The Original Microservices", loc = "/blog/the-original-microservices", desc = "Unix had single responsibility, API contracts, message queues, and service discovery in 1973. The industry repackaged it and called it microservices." },
    { date = "Sun, 22 Feb 2026 00:00:00 GMT", title = "JavaScript Bloat: The Battery Tax", loc = "/blog/the-javascript-tax", desc = "558 KB median JavaScript per page. 44 per cent never executes. Mobile parses 25x slower than your dev machine." },
    { date = "Sat, 21 Feb 2026 00:00:00 GMT", title = "Markdown: The File That Outlives the Company", loc = "/blog/the-markdown-replacement", desc = "John Gruber wrote the specification in 2004. A Perl script. 1,122 lines. Twenty-two years later, the format has not changed. It is text. Your Confluence export has already lost its macros." },
    { date = "Fri, 20 Feb 2026 00:00:00 GMT", title = "The Scrum Tax", loc = "/blog/the-scrum-tax", desc = "Six developers, 80 hours of sprint, 18 hours of ceremonies. A Scrum Master who costs $126k and requires no technical prerequisites." },
    { date = "Wed, 18 Feb 2026 00:00:00 GMT", title = "HTML Dialog: Modal or Not Modal", loc = "/blog/the-dialog-element", desc = "22.5 million npm installs per week for JavaScript that recreates the native dialog element. Focus traps, escape handlers, backdrop overlays. Every browser ships it. Since 2022." },
    { date = "Wed, 18 Feb 2026 00:00:00 GMT", title = "Bytes of Art: Neuron Activated", loc = "/blog/bytes-of-art-neuron-activated", desc = "5 kilobytes. One person. First place. Krzysztof Kluczek wrote the code, designed the visuals, and built a guitar synthesiser at Riverwash 2014." },
    { date = "Tue, 17 Feb 2026 00:00:00 GMT", title = "Technical Beauty: sed", loc = "/blog/technical-beauty-sed", desc = "A psychologist at Bell Labs writes a text editor that never opens a file. 53 years later, it runs everywhere. 25 commands, two buffers, one pass." },
    { date = "Mon, 16 Feb 2026 00:00:00 GMT", title = "Service Management: init vs systemd", loc = "/blog/init-vs-systemd", desc = "FreeBSD init runs on 178 shell scripts and one shared library. systemd ships 690,000 lines of C across 150 compiled binaries." },
    { date = "Sun, 15 Feb 2026 00:00:00 GMT", title = "The Webpack Tax", loc = "/blog/the-webpack-tax", desc = "Webpack solved a 2012 problem that ES Modules natively solved in 2017. esbuild is 106x faster. Vite cold-starts in 1.7 seconds." },
    { date = "Fri, 13 Feb 2026 00:00:00 GMT", title = "MongoDB: The Reinvention of the Wheel", loc = "/blog/the-mongodb-tax", desc = "MongoDB stores relational data in a document store, then spends a decade rebuilding the relational features it discarded." },
    { date = "Thu, 12 Feb 2026 00:00:00 GMT", title = "Unit Tests for Everything", loc = "/blog/unit-tests-for-everything", desc = "In 1994, Kent Beck wrote SUnit to test isolated units of logic. By 2015, the industry had turned his invention into a coverage KPI." },
    { date = "Wed, 11 Feb 2026 00:00:00 GMT", title = "The Specificity War Is Over", loc = "/blog/the-specificity-war", desc = "CSS Cascade Layers end the two-decade specificity war permanently. One declaration line sets the hierarchy. Layer order outranks specificity." },
    { date = "Tue, 10 Feb 2026 00:00:00 GMT", title = "mc: The Workstation in 12 MB", loc = "/blog/technical-beauty-mc", desc = "In 1994, a computer science student in Mexico City wrote a file manager. 31 years later, it runs on anything with a C compiler. 220,000 lines of C. 12 MB of RAM. Dual panels, built-in editor, FTP, SFTP, archive browsing. No venture capital." },
    { date = "Tue, 10 Feb 2026 00:00:00 GMT", title = "HTTP/2: The Bundling Myth", loc = "/blog/http2-the-bundling-myth", desc = "HTTP/1.1 made bundling necessary. HTTP/2 made it obsolete. Multiplexing, granular caching, and the rule that inverted itself a decade ago." },
    { date = "Mon, 09 Feb 2026 00:00:00 GMT", title = "ZFS Snapshots &amp; Boot Environments: The Safety Net", loc = "/blog/zfs-the-safety-net", desc = "Same ZFS, same commands, radically different experience. On FreeBSD, bectl is in base, the bootloader understands boot environments natively." },
    { date = "Mon, 09 Feb 2026 00:00:00 GMT", title = "ZFS Snapshots: Same Commands, Different Experience", loc = "/blog/zfs-snapshots", desc = "The ZFS commands are identical on FreeBSD and Linux. The snapshots work the same way. The difference is everything around them: kernel integration, boot environments, and what happens when you upgrade." },
    { date = "Sun, 08 Feb 2026 00:00:00 GMT", title = "Kubernetes: You Are Not Google", loc = "/blog/the-kubernetes-performance-tax", desc = "82 per cent of container users run Kubernetes in production. The control plane demands 12-24 GB RAM before your app serves one request." },
    { date = "Sun, 08 Feb 2026 00:00:00 GMT", title = "The Interpreted Stack", loc = "/blog/the-interpreted-stack", desc = "The job description is admirably brief: a request arrives, HTML leaves. And yet, a quarter century of accretion has produced something rather more elaborate." },
    { date = "Sat, 07 Feb 2026 00:00:00 GMT", title = "ORM: The Illusion of Portability", loc = "/blog/the-orm-illusion", desc = "ORMs hide complexity instead of eliminating it. They promise database portability you will never use and obscure queries you should understand." },
    { date = "Fri, 06 Feb 2026 00:00:00 GMT", title = "Docker: The Capitulation", loc = "/blog/the-docker-tax", desc = "Docker did not solve a technical problem. It monetised a political one. Linux could not agree on a base system, so the industry shipped the entire OS with every application." },
    { date = "Thu, 05 Feb 2026 00:00:00 GMT", title = "READS: The Five Prefixes", loc = "/blog/reads-the-five-prefixes", desc = "OOCSS arrived in 2009. BEM arrived in 2010. Both produce identical specificity. One reads like a sentence. The other reads like a German compound noun." },
    { date = "Thu, 05 Feb 2026 00:00:00 GMT", title = "MVC for Web", loc = "/blog/mvc-for-web", desc = "In 1979, Trygve Reenskaug invented MVC for Smalltalk desktop applications. Then Ruby on Rails borrowed the terminology for the web." },
    { date = "Wed, 04 Feb 2026 00:00:00 GMT", title = "Technical Beauty: Redis", loc = "/blog/technical-beauty-redis", desc = "Salvatore Sanfilippo built Redis in 2009. Single-threaded by design. One event loop, no locks. 100,000+ operations per second on modest hardware." },
    { date = "Mon, 03 Feb 2026 00:00:00 GMT", title = "man: Read the Manual. It's Already Installed.", loc = "/blog/technical-beauty-man", desc = "Ken Thompson wrote the first man pages for Unix Version 1 in 1971. Fifty-five years later, the format remains. One structure. Every tool. Always. Offline documentation that matches the version you are actually running." },
    { date = "Sun, 01 Feb 2026 00:00:00 GMT", title = "Technical Beauty: ZFS", loc = "/blog/technical-beauty-zfs", desc = "Jeff Bonwick and Matthew Ahrens built ZFS at Sun Microsystems in 2005. Filesystems trusted hardware that lies. ZFS trusts mathematics instead." },
    { date = "Sun, 01 Feb 2026 00:00:00 GMT", title = "Technical Beauty: OpenSSH", loc = "/blog/technical-beauty-openssh", desc = "Theo de Raadt forked SSH in 1999. The original was accumulating licence restrictions. OpenSSH stripped it down, audited everything, and assumed the network is hostile." },
    { date = "Sun, 01 Feb 2026 00:00:00 GMT", title = "Team Autonomy: The Balkanisation", loc = "/blog/the-balkanisation", desc = "Four teams, four frameworks, four pipelines, four security postures. A cross-team feature ships in month three." },
    { date = "Sun, 01 Feb 2026 00:00:00 GMT", title = "The Framework Tax", loc = "/blog/the-framework-tax", desc = "In 2010, vanilla JavaScript built the web. In 2026, a React Hello World installs 2,839 packages." },
    { date = "Sat, 31 Jan 2026 00:00:00 GMT", title = "From REST Ceremony to JSON-RPC", loc = "/blog/the-json-rpc-replacement", desc = "Five HTTP verbs. Fifty status codes. URL hierarchies. Content negotiation. All to answer: client wants something from server. JSON-RPC answered that in 2005." },
    { date = "Fri, 30 Jan 2026 00:00:00 GMT", title = "Serverless: What You Actually Pay", loc = "/blog/the-serverless-tax", desc = "Serverless is not serverless. It is MicroVMs with amnesia, vendor lock-in with four incompatible dialects, and cold starts." },
    { date = "Fri, 30 Jan 2026 00:00:00 GMT", title = "Technical Beauty: rsync", loc = "/blog/technical-beauty-rsync", desc = "Andrew Tridgell had a problem in 1996: synchronising files over slow links. rsync splits files into chunks, computes rolling checksums, and transfers only the differences." },
    { date = "Thu, 29 Jan 2026 00:00:00 GMT", title = "Technical Beauty: FFmpeg", loc = "/blog/technical-beauty-ffmpeg", desc = "Fabrice Bellard started FFmpeg in 2000. The multimedia world was fragmented. FFmpeg handles every format ever created. 1.5 million lines of C." },
    { date = "Thu, 29 Jan 2026 00:00:00 GMT", title = "Technical Beauty: tar", loc = "/blog/technical-beauty-tar", desc = "1979. John Gilmore writes tar for Unix V7. Tape ARchive. One format, one purpose: bundle files into a stream. Every container image is a stack of tarballs." },
    { date = "Thu, 29 Jan 2026 00:00:00 GMT", title = "OKLCH: The Colour System That Does Not Lie", loc = "/blog/oklch-colour-system", desc = "For three decades, CSS lied about lightness. HEX told you nothing. HSL promised perceptual uniformity and delivered optical illusion. OKLCH fixes the problem." },
    { date = "Wed, 28 Jan 2026 00:00:00 GMT", title = "Technical Beauty: tmux", loc = "/blog/technical-beauty-tmux", desc = "Nicholas Marriott wrote tmux in 2007 because GNU Screen had accumulated three decades of cruft. BSD-licensed. 60,000 lines of C." },
    { date = "Wed, 28 Jan 2026 00:00:00 GMT", title = "The Replacement: FreeBSD Jails", loc = "/blog/the-jails-replacement", desc = "Docker needs a daemon, image layers, a registry, overlay networks. FreeBSD Jails need a directory and a config file. Native kernel isolation since 2000." },
    { date = "Tue, 27 Jan 2026 00:00:00 GMT", title = "From PHP to Rust: Why I Skipped Go", loc = "/blog/the-rust-replacement", desc = "After 20 years of PHP, I needed something new. Everyone said Go. I chose Rust instead. The compiler is your private tutor." },
    { date = "Tue, 27 Jan 2026 00:00:00 GMT", title = "pf vs nftables: Bruteforce", loc = "/blog/pf-vs-nftables", desc = "Fresh server, SSH open, auth.log fills up. Linux reaches for fail2ban, a Python daemon that parses logs after the fact. FreeBSD solves it in four lines of pf.conf." },
    { date = "Mon, 26 Jan 2026 00:00:00 GMT", title = "The Linux Compatibility Layer", loc = "/blog/the-linux-compatibility-layer", desc = "FreeBSD runs Linux binaries natively. No emulator. No VM. No container. The kernel translates syscalls in real time, at less than 1% overhead. Since 1995." },
    { date = "Sat, 25 Jan 2026 00:00:00 GMT", title = "SSH + Shell: The Configuration Management You Already Have", loc = "/blog/the-ssh-shell-replacement", desc = "Ansible solves a problem that SSH, a for loop, and configs in git solved twenty years earlier. For five servers, you do not need a framework. You need a shell script." },
    { date = "Sun, 25 Jan 2026 00:00:00 GMT", title = "TypeScript: The Build Tax", loc = "/blog/typescript-the-build-tax", desc = "ECMAScript is a complete language. Types are not missing from JavaScript: they were never part of the specification." },
    { date = "Sat, 24 Jan 2026 00:00:00 GMT", title = "CI/CD Pipelines: What You Actually Pay", loc = "/blog/the-cicd-tax", desc = "45-minute pipelines, 20 per cent of the work week lost to YAML, and a supply chain that leaked 23,000 repositories of secrets." },
    { date = "Fri, 23 Jan 2026 00:00:00 GMT", title = "Technical Beauty: Lua", loc = "/blog/technical-beauty-lua", desc = "25,000 lines of C. A 200 KB binary. Embedded in World of Warcraft, Lightroom, nginx, Redis, Neovim, Roblox, Nmap. Born from Brazilian trade barriers." },
    { date = "Thu, 22 Jan 2026 00:00:00 GMT", title = "Bytes of Art: Prelude to Neobyte", loc = "/blog/bytes-of-art-prelude-to-neobyte", desc = "240 by 136 pixels. 16 colours. 4 audio channels. TIC-80 deliberately mimics 1980s hardware. Spectrox squeezed voxel landscapes and copper bar effects out of those constraints. Second place at Deadline Berlin 2025." },
    { date = "Tue, 20 Jan 2026 00:00:00 GMT", title = "Technical Beauty: awk", loc = "/blog/technical-beauty-awk", desc = "Aho, Weinberger, Kernighan. 1977. A pattern-action language for text processing. One pass through the data. No compilation." },
    { date = "Mon, 19 Jan 2026 00:00:00 GMT", title = "The Pattern", loc = "/blog/the-pattern", desc = "Over eight episodes we dissected individual performance problems. Stand back far enough and a shape emerges. The same shape, every time." },
    { date = "Sun, 18 Jan 2026 00:00:00 GMT", title = "Bytes of Art: Clean Slate", loc = "/blog/bytes-of-art-clean-slate", desc = "65,536 bytes. Three people. A real-time rendered film with physically-based rendering, volumetric lighting, procedural everything." },
    { date = "Sun, 18 Jan 2026 00:00:00 GMT", title = "The Monitoring Replacement", loc = "/blog/the-monitoring-replacement", desc = "Prometheus needs 2 GB RAM to monitor 10 services. The Unix shell has had monitoring since 1971: ps, top, vmstat, netstat." },
    { date = "Sat, 17 Jan 2026 00:00:00 GMT", title = "Event Sourcing: The Archaeology Tax", loc = "/blog/the-event-sourcing-tax", desc = "Complete audit trail! Time travel! A shopping cart with 10 items produces 13+ events. A 3 TB replay takes 10 hours." },
    { date = "Sat, 17 Jan 2026 00:00:00 GMT", title = "The SSH Replacement", loc = "/blog/the-ssh-replacement", desc = "SSH plus shell replaces Ansible, Python, YAML, Jinja2, inventory files, role dependencies, and Galaxy collections." },
    { date = "Thu, 15 Jan 2026 00:00:00 GMT", title = "Bytes of Art: The Scene Is Dead", loc = "/blog/bytes-of-art-scene-is-dead", desc = "Razor 1911, founded 1985. Their 2012 demo is 64 kilobytes of irony: CRT scanlines, Dubmood's soundtrack, and a running gag." },
    { date = "Wed, 14 Jan 2026 00:00:00 GMT", title = "The Ones I Can't Show You", loc = "/blog/technical-beauty-closed-source", desc = "Some of the most elegant systems ever built are behind closed doors. QNX fit a complete POSIX OS on a 1.44 MB floppy. BeOS had pervasive multithreading before anyone understood why. NeXTSTEP gave us the web browser and macOS." },
    { date = "Wed, 14 Jan 2026 00:00:00 GMT", title = "Agile Estimation Theatre", loc = "/blog/agile-estimation-theatre", desc = "Story points were invented to stop managers converting estimates into deadlines. Then the industry converted story points into deadlines." },
    { date = "Wed, 14 Jan 2026 00:00:00 GMT", title = "Native Form Validation: The Library You Never Needed", loc = "/blog/the-native-form", desc = "44 KB of JavaScript to accomplish what HTML does with five characters. The browser validates. Accessible by default. Since 2014." },
    { date = "Tue, 13 Jan 2026 00:00:00 GMT", title = "Technical Beauty: cron", loc = "/blog/technical-beauty-cron", desc = "One loop. One file. Every minute. Since 1975. Ken Thompson wrote the first version at Bell Labs. Paul Vixie rewrote it in 1987. 2,500 lines of C." },
    { date = "Mon, 12 Jan 2026 00:00:00 GMT", title = "Bytes of Art: Zetsubo", loc = "/blog/bytes-of-art-zetsubo", desc = "4,096 bytes. A complete audiovisual experience: procedural geometry, synthesised soundtrack, real-time rendering. Prismbeings, 2018." },
    { date = "Thu, 08 Jan 2026 00:00:00 GMT", title = "htop: 20 Years of Treating the Terminal as a Canvas", loc = "/blog/technical-beauty-htop", desc = "In 2004, Hisham Muhammad looked at top and saw a tool from 1984 pretending the terminal was still a teletype. One binary replaced an entire workflow: top, ps, grep, kill, renice, lsof. 12,000 lines of C. Zero configuration." },
    { date = "Fri, 09 Jan 2026 00:00:00 GMT", title = "The Cloud-Native Tax", loc = "/blog/the-cloud-native-tax", desc = "The bill is 47 pages and requires a FinOps specialist to decode. Netflix uses AWS for the back office. For video delivery: FreeBSD, jails, bare metal." },
    { date = "Wed, 07 Jan 2026 00:00:00 GMT", title = "Vanilla JS: The Framework You Already Have", loc = "/blog/vanilla-js-the-framework-you-have", desc = "React ships 142 KB before your code runs. The browser ships querySelector, addEventListener, Web Components, Proxy, and fetch. Zero kilobytes." },
    { date = "Wed, 07 Jan 2026 00:00:00 GMT", title = "Technical Beauty: age", loc = "/blog/technical-beauty-age", desc = "Filippo Valsorda wrote age because GPG had become unusable. One binary. One command to encrypt. One command to decrypt. No key servers, no web of trust." },
    { date = "Tue, 06 Jan 2026 00:00:00 GMT", title = "Technical Beauty: FreeBSD Jails", loc = "/blog/technical-beauty-jails", desc = "Poul-Henning Kamp built FreeBSD Jails in 1999. Kernel-level isolation, near-zero overhead. Stable API for 25 years. No daemon, no overlay network." },
    { date = "Mon, 05 Jan 2026 00:00:00 GMT", title = "The CSS-in-JS Tax", loc = "/blog/the-css-in-js-tax", desc = "CSS-in-JS is writing CSS in JavaScript to generate CSS. The runtime overhead, the 13 KB library tax, hydration roulette." },
    { date = "Sun, 04 Jan 2026 00:00:00 GMT", title = "Vanilla CSS: The Sass Replacement", loc = "/blog/the-sass-replacement", desc = "Sass was revolutionary in 2012. Variables, nesting, functions. In 2026, CSS does all of it natively. No build step. No node-sass conflicts." },
    { date = "Sat, 03 Jan 2026 00:00:00 GMT", title = "AI Agents Waste More Compute on Padding Than on Answers", loc = "/blog/ai-padding-waste", desc = "Defensive loops, trained hedging, three tool-calls where one would do. Data centres humming at full capacity. Not for answers. For comfort. The demoscene taught me: 4 KB leaves no space for bullshit." },
    { date = "Fri, 02 Jan 2026 00:00:00 GMT", title = "The npm Tax", loc = "/blog/the-npm-tax", desc = "That sentence has done more damage to software security than any zero-day exploit. It installs 1,400 packages before your kettle has boiled." },
    { date = "Wed, 31 Dec 2025 00:00:00 GMT", title = "The SPA Tax", loc = "/blog/the-spa-tax", desc = "We need a Single Page Application. A perfectly reasonable sentence, provided one does not ask the follow-up question." },
    { date = "Tue, 30 Dec 2025 00:00:00 GMT", title = "Technical Beauty: nginx", loc = "/blog/technical-beauty-nginx", desc = "Igor Sysoev built nginx in 2004 because Apache's thread-per-connection model was architecturally wrong. Event-driven, pure C, no framework." },
    { date = "Mon, 29 Dec 2025 00:00:00 GMT", title = "The Angular Tax", loc = "/blog/the-angular-tax", desc = "Angular is the SAP of frontend frameworks. Zone.js monkey-patches 30+ browser APIs, a Hello World ships 500 KB, and Google builds Angular but does not use it." },
    { date = "Sun, 28 Dec 2025 00:00:00 GMT", title = "Agile: The Hostile Takeover", loc = "/blog/agile-the-hostile-takeover", desc = "Divide and conquer. The oldest strategy of control. Fragment the opposition. Isolate the units. They call it Agile." },
    { date = "Sat, 27 Dec 2025 00:00:00 GMT", title = "The Kubernetes Tax", loc = "/blog/the-kubernetes-tax", desc = "81 resource types. 200 lines of YAML to replace one systemctl command. A platform team before your first customer." },
    { date = "Fri, 26 Dec 2025 00:00:00 GMT", title = "Technical Beauty: curl", loc = "/blog/technical-beauty-curl", desc = "Daniel Stenberg released curl in 1998. 26 years, zero breaking changes, one dependency: libc. Runs on 10+ billion devices." },
    { date = "Wed, 24 Dec 2025 00:00:00 GMT", title = "Technical Beauty: PostgreSQL", loc = "/blog/technical-beauty-postgresql", desc = "Michael Stonebraker built POSTGRES at Berkeley in 1986. Minimal core, everything extensible. 38 years, same BSD licence. No corporate owner." },
    { date = "Tue, 23 Dec 2025 00:00:00 GMT", title = "Technical Beauty: git", loc = "/blog/technical-beauty-git", desc = "Linus Torvalds built git in ten days. 10 MB, no server, no database, no dependencies beyond libc. Content-addressable, distributed, backwards compatible since 2005." },
    { date = "Mon, 22 Dec 2025 00:00:00 GMT", title = "The Flexbox Tax", loc = "/blog/the-flexbox-tax", desc = "Flexbox arrived to solve layout. Then the industry used it for everything. Twelve wrapper divs for a holy grail layout that CSS Grid solves in three lines." },
    { date = "Sun, 21 Dec 2025 00:00:00 GMT", title = "The Browser Is Not a JavaScript Runtime", loc = "/blog/javascript-overuse", desc = "80% of the JavaScript on modern websites solves problems that do not exist anymore. Accordions, modals, form validation, lazy loading. The browser ships all of it. Zero kilobytes." },
    { date = "Sat, 20 Dec 2025 00:00:00 GMT", title = "The Microservices Tax", loc = "/blog/the-microservices-tax", desc = "But deployments are cleaner! That sentence has launched more Kubernetes clusters than any legitimate scaling requirement." },
    { date = "Wed, 17 Dec 2025 00:00:00 GMT", title = "WireGuard: The VPN That Fits in Your Head", loc = "/blog/technical-beauty-wireguard", desc = "Jason Donenfeld built WireGuard in 4,000 lines of code. OpenVPN needs 100,000. Linus Torvalds called it a work of art." },
    { date = "Tue, 16 Dec 2025 00:00:00 GMT", title = "Technical Beauty: SQLite", loc = "/blog/technical-beauty-sqlite", desc = "D. Richard Hipp built SQLite in 2000 for a US Navy destroyer. 600 KB, single file, zero configuration. Public domain. Supported until 2050." },
    { date = "Mon, 15 Dec 2025 00:00:00 GMT", title = "The React Tax", loc = "/blog/the-react-tax", desc = "React 18 ships 136 KB minified before you have written a single line of application code. The Virtual DOM costs 30 per cent versus vanilla JavaScript." },
    { date = "Sun, 14 Dec 2025 00:00:00 GMT", title = "Native ES Modules: The Replacement", loc = "/blog/the-esmodules-replacement", desc = "Browsers have understood ES Modules since 2018. HTTP/2 solved the request overhead in 2015. For 90% of projects, the build pipeline is the complexity." },
    { date = "Sun, 07 Dec 2025 00:00:00 GMT", title = "Shallow Errors", loc = "/blog/shallow-errors", desc = "In 2013, a German data scientist discovered Xerox scanners were silently changing numbers in scanned documents. No error. No warning." },
    { date = "Sun, 07 Dec 2025 00:00:00 GMT", title = "The Caddy Replacement", loc = "/blog/the-caddy-replacement", desc = "Caddy replaces Nginx, Certbot, Cron, and renewal hooks. One binary. Zero TLS configuration. Auto HTTPS since 2015." },
    { date = "Thu, 25 Dec 2024 00:00:00 GMT", title = "The Quiet Web", loc = "/blog/the-quiet-web", desc = "The web got far too loud. Pop-overs, cookie banners, newsletter modals, autoplay, scroll-jacking. The native dialog element and one preferences wizard replace every banner. Zero interruptions." },
    { date = "Wed, 18 Dec 2024 00:00:00 GMT", title = "The MVC Myth", loc = "/blog/the-mvc-myth", desc = "MVC was invented in 1979 for Smalltalk desktop GUIs. The web has no persistent controller, no event loop, no state between requests. 30% performance overhead from abstraction layers that serve no purpose in HTTP." },
}

local function escape(s)
    s = s:gsub("&", "&amp;")
    s = s:gsub("<", "&lt;")
    s = s:gsub(">", "&gt;")
    s = s:gsub("\"", "&quot;")
    s = s:gsub("'", "&apos;")
    return s
end

function route()
    local xml = '<?xml version="1.0" encoding="UTF-8"?>\n'
    xml = xml .. '<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">\n'
    xml = xml .. '<channel>\n'
    xml = xml .. '  <title>Vivian Voss</title>\n'
    xml = xml .. '  <link>' .. SITE .. '/blog</link>\n'
    xml = xml .. '  <description>Software architecture, Unix philosophy, and the demoscene. Selected articles by Vivian Voss.</description>\n'
    xml = xml .. '  <language>en-gb</language>\n'
    xml = xml .. '  <atom:link href="' .. SITE .. '/feed" rel="self" type="application/rss+xml"/>\n'

    for _, a in ipairs(articles) do
        xml = xml .. '  <item>\n'
        xml = xml .. '    <title>' .. escape(a.title) .. '</title>\n'
        xml = xml .. '    <link>' .. SITE .. a.loc .. '</link>\n'
        xml = xml .. '    <guid isPermaLink="true">' .. SITE .. a.loc .. '</guid>\n'
        xml = xml .. '    <pubDate>' .. a.date .. '</pubDate>\n'
        xml = xml .. '    <description>' .. escape(a.desc) .. '</description>\n'
        xml = xml .. '  </item>\n'
    end

    xml = xml .. '</channel>\n'
    xml = xml .. '</rss>\n'

    cn.res.header("Content-Type", "application/rss+xml; charset=utf-8")
    cn.res.header("Cache-Control", "public, max-age=3600")
    cn.res.body(xml)
end
